Update bio
jupytercon/2020-OpenSourceCommunities pull request #1
Opened 2020-09-29 21:06 UTC by malvikasharan

Ask Gabi to add her details and confirm adding her image

2020-09-29 21:08 UTC, malvikasharan commented
Hey Gabi, I have added some initial files: [README](./README.md), [CONTRIBUTING](./CONTRIBUTING.md), [LICENSE](./LICENSE.md), and [CoC](./CODE_OF_CONDUCT.md). Can you please also have a look at those and confirm you are happy with it.

2020-09-30 02:59 UTC, gdequeiroz requested changes
LGTM

2020-09-30 02:59 UTC, gdequeiroz commented on CODE_OF_CONDUCT.md
> +and Gabriela de Quieroz (email: contactkroz@gmail.com).
Quieroz -> Queiroz

2020-09-30 07:47 UTC, malvikasharan commented on CODE_OF_CONDUCT.md
> +and Gabriela de Quieroz (email: contactkroz@gmail.com).
Done!

2020-09-30 07:47 UTC, merged